### PR TITLE
Allure crawler

### PR DESCRIPTION
**Pull request by eroshenkoam**

### CODE REVIEW

**Comment by eroshenkoam** [comment]
@daniel-beck can you merge this pr?

**Comment by daniel-beck** [comment]
Have you tried running this? Isn't it missing the shebang line?

**Comment by eroshenkoam** [comment]
@daniel-beck I fix it and squash changes into one commit.
Now its work fine.

**Comment by daniel-beck** [comment]
Merged and triggered a crawler run. Appears to work fine.

**Pull request merged**
