### PR TITLE
Adding iojs

### PR DESCRIPTION
**Pull request by jhinrichsen**
io.js is a fork of NodeJS

### CODE REVIEW

**Comment by daniel-beck** [comment]
Reference: https://groups.google.com/d/msg/jenkinsci-dev/Fekq5TTO2bo/Lelfm-QPiOIJ

**Comment by daniel-beck** [comment]
@jhinrichsen Is this still needed?

**Comment by jhinrichsen** [comment]
No, both node.js and its fork io.js have decided to merge again and created a Version Node.js 4.0.0. This version can already be installed via the existing Node Plugin.

So whatever the process is that deprecates/ removes/ starts end-of-lifecycle, we can start it for the io.js plugin.

**Comment by daniel-beck** [comment]
@jhinrichsen We dropped the ball on creating the fork, and the plugin has never been released from what the update site looks like. Nothing to clean up AFAICT.

**Pull request closed without merging**
