### PR TITLE
Correctly find the highest version number for chromedriver

### PR DESCRIPTION
**Pull request by Mobrockers**
Relates to issue https://issues.jenkins-ci.org/browse/JENKINS-33270 

Perhaps there's a better way to get the latest version number, but I am not familiar with groovy, and this seems to work.

### CODE REVIEW

**Comment by Mobrockers** [comment]
Does anyone have any thoughts on this? Improvements, suggestions, or does it look good as it is?

**Comment by Mobrockers** [comment]
@orrc @daniel-beck @kohsuke Any thoughts? Can this be merged? Would love to hear from anyone.

**Comment by Mobrockers** [comment]
Ping @kohsuke

**Comment by daniel-beck** [comment]
Let's see what happens :smile:

**Comment by daniel-beck** [comment]
Looks good in the build log.

**Comment by Mobrockers** [comment]
Thanks!

**Comment by Mobrockers** [comment]
@daniel-beck Quick question. Does this require a new jenkins release before the change is live? Or can I re-enable the jenkins plugin that uses the chrome-driver binary downloaded by this script right now?

**Comment by daniel-beck** [comment]
@Mobrockers No, this is part of the Jenkins project infrastructure. The build I was mentioning provides the metadata to http://updates.jenkins-ci.org/updates/ from which Jenkins downloads it.

Between our mirror network being slow to update, and your Jenkins caching this data for a day or so, it may take a while to show up, so in the meantime, enjoy the fixed content at the source:
**New**: https://ci.jenkins-ci.org/job/infra_backend_crawler/296/artifact/target/org.jenkins-ci.plugins.chromedriver.ChromeDriver.json/*view*/
**Old**: https://ci.jenkins-ci.org/job/infra_backend_crawler/295/artifact/target/org.jenkins-ci.plugins.chromedriver.ChromeDriver.json/*view*/

**Comment by Mobrockers** [comment]
@daniel-beck thank you :clap:

**Pull request merged**
