### PR TITLE
allure2 integration

### PR DESCRIPTION
**Pull request by eroshenkoam**

### CODE REVIEW

**Comment by eroshenkoam** [comment]
@daniel-beck can we merge this pr?

**Comment by daniel-beck** [comment]
@eroshenkoam I will merge this once I had time to review and the time to monitor the first run (or set up PR builds for this repo \*sigh\*).

**Comment by eroshenkoam** [comment]
@daniel-beck I can help you with that. 
Here is the first draft of Jenkinsfile: 
https://github.com/jenkinsci/backend-crawler/pull/60

**Comment by daniel-beck** [comment]
This results in a list of lists. I have aborted publication until this is clarified.

**Comment by daniel-beck** [comment]
@eroshenkoam This isn't what you wanted, is it? https://gist.github.com/daniel-beck/b36ea2b01d1d7e946e6475e46f45f3b2

**Comment by daniel-beck** [comment]
@eroshenkoam Ping

**Comment by eroshenkoam** [comment]
@daniel-beck yes

**Comment by daniel-beck** [comment]
@eroshenkoam To clarify, I reverted this in https://github.com/jenkins-infra/crawler/pull/61 because the output looked wrong. Could you confirm this format is (not) what you were expecting? If yes, I'll restore it; if no, please submit a new PR.

**Pull request merged**
