### PR TITLE
[INFRA-181] detect maven binaries release on new layout

### PR DESCRIPTION
**Pull request by ebarboni**
maven 3 binaries are released in http://archive.apache.org/dist/maven/maven-3/ instead of http://archive.apache.org/dist/maven/binaries/

Proposed PR 
1) scan maven-3 folder in order to get the available version.
2) From a given version url it scan all artifacts to get the zip binaries as it was previoulsy done for ant (and older maven binaires layout)

-- add to factorize sorting closure for better readability

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Would it be better to get them off http://repo1.maven.org/maven2/org/apache/maven/apache-maven/ as the archive only contains older releases?

**Comment by ebarboni** [comment]
Taking from repo1.maven.org seems safer, but I don't kown the rationale of taking maven zip from archive.

**Comment by zregvart** [comment]
I've reworked the patch by Eric Barboni with regards to suggestions by David J. M. Karlsen -- to use only maven central. This narrows the maven support to versions 2.0.9 onward, but it's somewhat simpler.

See https://github.com/zregvart/backend-crawler/commit/23c03462a688eb7c6db46209c0dbd1ff0328e464.

**Comment by aheritier** [comment]
Superseded by in #35 Thx for your help

**Comment by ebarboni** [comment]
closing as #35 is based on discussion with maven dev

**Pull request closed without merging**
